### ISSUE TITLE
macOSX preferences

### ISSUE THREAD

**Issue by salambra79** [Sciss/FScape#9]
Hi mr. Hanns.
Does FScapre works in macOS 10.5.8?
Thank you!

**Comment by Sciss** [comment]
Probably that's too old. Note that 10.6 came out in 2009! Before I switched to Linux, I mostly used 10.6 (Snow Leopard). FScape was always compatible with Java 6, although in #7 a class file dependency on Java 8 was introduced. You can check your Java version from a terminal (Utilities > Terminal.app) running `java -version`. If you can get Java 6 to run on your system, I should be able to fix #7. Any reason not update to a newer OS?

**Comment by salambra79** [comment]
Yes you are right, I should update, but I dont know if some software I use will work in a newer version-like Audiosculpt 3 from Ircam for example, and I'm not able to pay for a newer version of Audiosculpt.
Is there a way to just update to 10.6.8? I think that will not cause any issues with my softs.

**Comment by Sciss** [comment]
Since I left macOS some time ago, I don't really know if you can run a limited update to 10.6.8. You could check the system's software update feature to see if it allows you to upgrade. Probably you will need an installer DVD. But you can check first from the terminal which Java version (if any) you have installed. If you can get Java 6 (aka 1.6) to work on your current system, it will be possible to run FScape (when I have patched it).

**Comment by Sciss** [comment]
P.S. From what I read, you should be able to install Java 1.6 or even 1.7 on Mac OS X Leopard (10.5)

**Comment by Sciss** [comment]
Newly released 1.5.0 should fix Java 6 incompatibilities (not tested, though): https://github.com/Sciss/FScape/releases/tag/v1.5.0

**Comment by salambra79** [comment]
SUCCESS!
I found a download for java 1.6-went to java preferences to select the correct version and FScape 1.5 works perfect!
Thank you very much for your time and your research for my issue.
